name: Deploy
on: [push,pull_request]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
      
      - name: install and run build
        run: |
          npm ci
          npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: my-project # TODO: update with the name of the project on Deno Deploy
          entrypoint: ./index.js
          root: build